/*
 * generated by Xtext 2.16.0
 */
package org.uniovi.miw.jgen


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JGenStandaloneSetup extends JGenStandaloneSetupGenerated {

	def static void doSetup() {
		new JGenStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
