/*
 * generated by Xtext 2.16.0
 */
package org.uniovi.miw.jgen

import org.eclipse.xtext.conversion.IValueConverterService
import org.uniovi.miw.jgen.valueconverters.CustomValueConverter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class JGenRuntimeModule extends AbstractJGenRuntimeModule {
	override Class<? extends IValueConverterService> bindIValueConverterService() {
		return CustomValueConverter 
	}
}
